import type { Agent, AgentEvent, Alert, GraphEdge, GraphNode, Log, Task, Workflow } from './types'

export const AGENTS: Agent[] = [
  {
    id: 'hermes',
    name: 'Hermes Agent',
    role: 'Local LLM orchestration',
    description: 'Central coordinator for prompts, memory routing, Graphify updates, and agent handoffs.',
    icon: 'H',
    color: '#7C5CFC',
    accent: '#A48BFF',
    status: 'online',
    health: 98.5,
    tasks: 12,
    queue: 3,
    latencyMs: 420,
    tokensToday: 184200,
    costToday: 3.72,
    memoryItems: 412,
    graphEvents: 64,
    goalProgress: 78,
    currentAction: 'Routing prompt across Claude, OpenCode and OpenClaw',
    currentWorkflow: 'Graph Memory Sync',
    currentGoal: 'Coordinate every tool lane',
    lastAction: 'Wrote 3 new memory records',
    thought: 'Graphify communities drifted — splitting engineering from orchestration before next sprint review.',
    decision: 'Approve workspace redesign contract and assign OpenCode for implementation.',
    toolUsage: ['graphify.update', 'telegram.broadcast', 'ollama.prompt'],
    execution: 'Clustered 7 communities, indexed 412 memory records, 0 failures.',
    tools: ['ollama', 'graphify', 'telegram', 'discord'],
    goals: ['Coordinate every tool lane', 'Keep Graphify current', 'Minimize duplicate agent work'],
    memory: ['System topology', 'Agent tool permissions', 'Escalation rules'],
    collaborators: ['claude', 'opencode', 'openclaw'],
  },
  {
    id: 'claude',
    name: 'Claude Code',
    role: 'Deep engineering agent',
    description: 'Handles complex architecture, refactors, tests, and production-grade code review.',
    icon: 'C',
    color: '#FF5252',
    accent: '#FF7E7E',
    status: 'online',
    health: 99.1,
    tasks: 24,
    queue: 6,
    latencyMs: 860,
    tokensToday: 241800,
    costToday: 11.42,
    memoryItems: 286,
    graphEvents: 31,
    goalProgress: 72,
    currentAction: 'Reviewing Agent Workspace redesign',
    currentWorkflow: 'Code Change Verification',
    currentGoal: 'Ship production UI',
    lastAction: 'Verified React build after type cleanup',
    thought: 'Verifying depth, perspective, motion contracts before approving OpenCode implementation.',
    decision: 'Approve sidebar perspective layer and hand off to OpenCode.',
    toolUsage: ['claude_code.review', 'tsc.typecheck', 'vitest.run'],
    execution: 'Reviewed 412 LOC, 0 criticals, 12 nit suggestions.',
    tools: ['claude_code', 'tests', 'git'],
    goals: ['Ship production UI', 'Protect code quality', 'Close failing build loops'],
    memory: ['React app structure', 'Vite/Tailwind config', 'Dashboard redesign decisions'],
    collaborators: ['hermes', 'opencode'],
  },
  {
    id: 'opencode',
    name: 'OpenCode',
    role: 'Fast implementation lane',
    description: 'Executes focused code edits, small features, and rapid iteration loops.',
    icon: 'O',
    color: '#FFD600',
    accent: '#FFE94D',
    status: 'busy',
    health: 97.8,
    tasks: 18,
    queue: 4,
    latencyMs: 310,
    tokensToday: 128900,
    costToday: 1.88,
    memoryItems: 174,
    graphEvents: 22,
    goalProgress: 66,
    currentAction: 'Compacting Agent Workspace components',
    currentWorkflow: 'Code Change Verification',
    currentGoal: 'Implement minimal clean changes',
    lastAction: 'Compacted workspace panels',
    thought: 'Density pass on dashboard panels and tightening AgentWorkspace props.',
    decision: 'Replace flat panels with floating depth layers; ship in 18m.',
    toolUsage: ['opencode.edit', 'vite.build', 'tsc.typecheck'],
    execution: 'Implemented 4 components, density +38%, 0 type errors.',
    tools: ['opencode', 'typescript', 'vite'],
    goals: ['Implement minimal clean changes', 'Keep iteration speed high', 'Avoid duplicated UI components'],
    memory: ['Component patterns', 'Known TypeScript errors', 'Build commands'],
    collaborators: ['claude', 'hermes'],
  },
  {
    id: 'openclaw',
    name: 'OpenClaw',
    role: 'Cloud execution surface',
    description: 'Runs cloud-heavy tasks, connectors, and remote automation workflows.',
    icon: 'W',
    color: '#00E5FF',
    accent: '#5DF1FF',
    status: 'online',
    health: 97.8,
    tasks: 8,
    queue: 2,
    latencyMs: 640,
    tokensToday: 76400,
    costToday: 4.16,
    memoryItems: 128,
    graphEvents: 18,
    goalProgress: 61,
    currentAction: 'Watching deployment connector health',
    currentWorkflow: 'Connector Health Sweep',
    currentGoal: 'Maintain connector uptime',
    lastAction: 'Connector synced with retry window extended',
    thought: 'Heartbeat drifted on prod-3 — escalating to Hermes before sprint review.',
    decision: 'Open incident and route to Hermes with extended retry window.',
    toolUsage: ['cloud.connector.sweep', 'scheduler.dispatch'],
    execution: '12 connectors checked, 11 synced, 1 retry window extended.',
    tools: ['cloud', 'connectors', 'scheduler'],
    goals: ['Maintain connector uptime', 'Run remote jobs', 'Detect integration drift'],
    memory: ['Connector contracts', 'Cloud job state', 'Retry windows'],
    collaborators: ['hermes'],
  },
]

export const TASKS: Task[] = [
  { id: '1', title: 'Launch first affiliate program', status: 'todo', priority: 'high', assignee: 'hermes', description: 'Pick top niche, configure tracking, assign content sprint.', time: '2d ago', created_at: '2026-06-22T09:15:44Z' },
  { id: '2', title: 'Wire real Graphify API into UI', status: 'in_progress', priority: 'high', assignee: 'claude', description: 'Replace mock nodes after visual brain stabilizes.', time: '5m ago', created_at: '2026-06-22T02:53:59Z' },
  { id: '3', title: 'Compact Agent Workspace layout', status: 'in_progress', priority: 'high', assignee: 'opencode', description: 'Reduce empty space and expose operational panels.', time: '12m ago', created_at: '2026-06-22T02:53:59Z' },
  { id: '4', title: 'Draft AgentOS launch narrative', status: 'todo', priority: 'medium', assignee: 'hermes', description: 'Write launch narrative grounded in graph memory.', time: '18m ago', created_at: '2026-06-22T02:53:59Z' },
  { id: '5', title: 'Test Discord channel bindings', status: 'done', priority: 'low', assignee: 'openclaw', description: 'All 6 channels verified.', time: '1h ago', created_at: '2026-06-22T02:53:59Z' },
  { id: '6', title: 'Backup Mission Control data', status: 'in_progress', priority: 'low', assignee: 'openclaw', description: 'Weekly cron into Graphify.', time: '3h ago', created_at: '2026-06-22T02:53:59Z' },
  { id: '7', title: 'Audit cloud cost ledger', status: 'review', priority: 'high', assignee: 'hermes', description: 'Token + cloud cost reconciliation before sprint review.', time: '4h ago', created_at: '2026-06-22T02:53:59Z' },
  { id: '8', title: 'Refactor sidebar perspective layer', status: 'in_progress', priority: 'medium', assignee: 'opencode', description: 'Replace flat panels with floating depth layers.', time: '5h ago', created_at: '2026-06-22T02:53:59Z' },
  { id: '9', title: 'Update graph communities after workspace rewrite', status: 'todo', priority: 'low', assignee: 'hermes', description: 'Run Graphify update after UI work.', time: '8h ago', created_at: '2026-06-22T02:53:59Z' },
  { id: '10', title: 'Resolve OpenClaw connector drift', status: 'blocked', priority: 'high', assignee: 'openclaw', description: 'Heartbeat windows drifted 3 cycles.', time: '2m ago', created_at: '2026-06-22T02:53:59Z' },
]

export const WORKFLOWS: Workflow[] = [
  { id: 'wf-1', name: 'Prompt to Production', status: 'running', owner: 'hermes', progress: 74, efficiency: 88, latency: '3m 42s', cost: '$0.72', runs: 128, failures: 3, steps: ['Hermes routes', 'Claude plans', 'OpenCode implements', 'Hermes verifies', 'OpenClaw deploys'] },
  { id: 'wf-2', name: 'Graph Memory Sync', status: 'running', owner: 'hermes', progress: 61, efficiency: 94, latency: '48s', cost: '$0.11', runs: 421, failures: 1, steps: ['Read logs', 'Extract entities', 'Update graph', 'Cluster communities'] },
  { id: 'wf-3', name: 'Code Change Verification', status: 'queued', owner: 'claude', progress: 38, efficiency: 76, latency: '11m 12s', cost: '$1.48', runs: 64, failures: 5, steps: ['Implement', 'Typecheck', 'Build', 'Review diff'] },
  { id: 'wf-4', name: 'Connector Health Sweep', status: 'failed', owner: 'openclaw', progress: 52, efficiency: 63, latency: '7m 03s', cost: '$0.39', runs: 87, failures: 9, steps: ['Ping connector', 'Collect latency', 'Classify failures', 'Open alert'] },
  { id: 'wf-5', name: 'Launch Sprint Rollup', status: 'completed', owner: 'hermes', progress: 100, efficiency: 91, latency: '2m 18s', cost: '$0.22', runs: 215, failures: 2, steps: ['Read tasks', 'Map goals', 'Summarize blockers', 'Write memory'] },
]

export const LOGS: Log[] = [
  { id: '1', agent_name: 'hermes', task_description: 'route: workspace redesign', model_used: 'minimax-m3:cloud', status: 'completed', level: 'info', source: 'hermes', message: 'Routed redesign request to Claude Code', time: '16:46', created_at: '2026-06-23T16:46:29Z' },
  { id: '2', agent_name: 'claude', task_description: 'review: graphify page', model_used: 'claude-code', status: 'started', level: 'info', source: 'claude', message: 'Started graph visual brain review', time: '16:44', created_at: '2026-06-23T16:44:25Z' },
  { id: '3', agent_name: 'openclaw', task_description: 'connector sweep', model_used: 'cloud-agent', status: 'failed', level: 'error', source: 'openclaw', message: 'Connector heartbeat drift exceeded retry threshold', time: '16:41', created_at: '2026-06-23T16:41:17Z' },
  { id: '4', agent_name: 'opencode', task_description: 'workspace compact pass', model_used: 'open-source-agent', status: 'started', level: 'debug', source: 'opencode', message: 'Compacting dashboard panel density', time: '16:28', created_at: '2026-06-23T16:28:54Z' },
  { id: '5', agent_name: 'hermes', task_description: 'graphify update', model_used: 'graphify', status: 'completed', level: 'info', source: 'system', message: 'Graph grew by 11 nodes and 18 relationships', time: '16:22', created_at: '2026-06-23T16:22:53Z' },
  { id: '6', agent_name: 'claude', task_description: 'typecheck', model_used: 'tsc', status: 'completed', level: 'info', source: 'dev', message: 'TypeScript build passed after model update', time: '16:19', created_at: '2026-06-23T16:19:51Z' },
]

export const ALERTS: Alert[] = [
  { id: '1', type: 'critical', title: 'OpenClaw connector drift', subtitle: 'Cloud connector heartbeat missed 3 windows.', time: '2m ago', source: 'OpenClaw', owner: 'openclaw', status: 'assigned', trend: 'up' },
  { id: '2', type: 'warning', title: 'Claude token spend spike', subtitle: 'Architecture review exceeded planned token budget.', time: '14m ago', source: 'Claude Code', owner: 'claude', status: 'assigned', trend: 'down' },
  { id: '3', type: 'warning', title: 'OpenCode review queue', subtitle: 'Five diffs awaiting architecture review.', time: '24m ago', source: 'OpenCode', owner: 'opencode', status: 'open', trend: 'flat' },
  { id: '4', type: 'info', title: 'Graphify community split', subtitle: 'Engineering and orchestration communities separated cleanly.', time: '38m ago', source: 'Hermes', owner: 'hermes', status: 'resolved', trend: 'flat' },
  { id: '5', type: 'success', title: 'Launch sprint rollup complete', subtitle: '5 goals updated, 1 blocker escalated.', time: '52m ago', source: 'Hermes', owner: 'hermes', status: 'resolved', trend: 'down' },
]

export const AGENT_EVENTS: AgentEvent[] = [
  { id: 'ev-1', agent: 'hermes', action: '→', target: 'claude', summary: 'Architecture review requested', detail: 'Workspace redesign contract', time: 'now', type: 'handoff' },
  { id: 'ev-2', agent: 'claude', action: '→', target: 'opencode', summary: 'Implementation approved', detail: 'Sidebar perspective layer signed off', time: '1m', type: 'handoff' },
  { id: 'ev-3', agent: 'opencode', action: '→', target: 'hermes', summary: 'Build completed', detail: 'TypeScript pass after refactor', time: '3m', type: 'task' },
  { id: 'ev-4', agent: 'openclaw', action: '→', target: 'hermes', summary: 'Connector synced', detail: 'Cloud job heartbeat recovered', time: '5m', type: 'task' },
  { id: 'ev-5', agent: 'hermes', action: '→', target: 'openclaw', summary: 'Connector sweep dispatched', detail: 'Retries with extended window', time: '7m', type: 'workflow' },
  { id: 'ev-6', agent: 'claude', action: '↻', target: 'opencode', summary: 'Review loop', detail: 'Sending back tighter type contracts', time: '9m', type: 'chat' },
  { id: 'ev-7', agent: 'hermes', action: '✓', target: 'graphify', summary: 'Communities updated', detail: '3 communities split', time: '12m', type: 'graph' },
  { id: 'ev-8', agent: 'opencode', action: '✓', target: 'hermes', summary: 'Compact pass delivered', detail: 'Density pass on workspace panels', time: '14m', type: 'memory' },
  { id: 'ev-9', agent: 'openclaw', action: '!', target: 'hermes', summary: 'Drift raised', detail: 'prod-3 heartbeat window drift', time: '16m', type: 'alert' },
  { id: 'ev-10', agent: 'hermes', action: '→', target: 'claude', summary: 'Sprint review prep', detail: 'Pulling narrative + design context', time: '18m', type: 'workflow' },
]

export const CONVERSATIONS = [
  { id: 'c1', participants: ['hermes', 'claude'], topic: 'Workspace redesign', last: 'Review signed off.', messages: 6, updated: '2m' },
  { id: 'c2', participants: ['claude', 'opencode'], topic: 'Type contract tightening', last: 'Re-export from sidebar layer.', messages: 4, updated: '4m' },
  { id: 'c3', participants: ['hermes', 'openclaw'], topic: 'Connector sweep', last: 'Drift mitigated, alert acknowledged.', messages: 5, updated: '7m' },
  { id: 'c4', participants: ['hermes', 'opencode'], topic: 'Density compact pass', last: 'Density +38% delivered.', messages: 3, updated: '14m' },
]

export const GRAPH_NODES: GraphNode[] = [
  { id: 'agentos', label: 'AgentOS', type: 'core', color: '#7C5CFC', community: 0, incoming: 9, outgoing: 7, weight: 14.4, x: 520, y: 320, summary: 'Central operating system and graph root.' },
  { id: 'hermes', label: 'Hermes', type: 'agent', color: '#7C5CFC', community: 0, incoming: 4, outgoing: 8, weight: 12.2, x: 320, y: 240, summary: 'Coordinator and graph router.' },
  { id: 'claude', label: 'Claude Code', type: 'agent', color: '#FF5252', community: 1, incoming: 3, outgoing: 5, weight: 11.0, x: 720, y: 220, summary: 'Deep engineering workspace.' },
  { id: 'opencode', label: 'OpenCode', type: 'agent', color: '#FFD600', community: 1, incoming: 3, outgoing: 4, weight: 9.8, x: 760, y: 430, summary: 'Fast implementation lane.' },
  { id: 'openclaw', label: 'OpenClaw', type: 'agent', color: '#00E5FF', community: 2, incoming: 3, outgoing: 4, weight: 9.2, x: 320, y: 470, summary: 'Cloud connector execution surface.' },
  { id: 'wf-prompt', label: 'Prompt to Production', type: 'workflow', color: '#7C5CFC', community: 0, incoming: 2, outgoing: 5, weight: 9.4, x: 520, y: 80, summary: 'End to end prompt pipeline.' },
  { id: 'wf-graph', label: 'Graph Memory Sync', type: 'workflow', color: '#A48BFF', community: 0, incoming: 2, outgoing: 4, weight: 8.6, x: 220, y: 110, summary: 'Memory and graph update workflow.' },
  { id: 'wf-code', label: 'Code Verification', type: 'workflow', color: '#FF5252', community: 1, incoming: 2, outgoing: 4, weight: 8.0, x: 880, y: 110, summary: 'Build, typecheck, review loop.' },
  { id: 'wf-connect', label: 'Connector Sweep', type: 'workflow', color: '#00E5FF', community: 2, incoming: 2, outgoing: 4, weight: 7.4, x: 220, y: 540, summary: 'Connector heartbeat and retry workflow.' },
  { id: 'goal-launch', label: 'AgentOS Launch', type: 'goal', color: '#A48BFF', community: 0, incoming: 4, outgoing: 1, weight: 11.4, x: 520, y: 0, summary: 'Primary business outcome.' },
  { id: 'goal-ui', label: 'Operational UI', type: 'goal', color: '#FF7E7E', community: 1, incoming: 3, outgoing: 1, weight: 9.6, x: 980, y: 320, summary: 'Operational UI redesign goal.' },
  { id: 'goal-uptime', label: 'Connector Uptime', type: 'goal', color: '#5DF1FF', community: 2, incoming: 2, outgoing: 1, weight: 8.4, x: 80, y: 320, summary: 'Maintain connector uptime.' },
  { id: 'task-affiliate', label: 'Affiliate Program', type: 'task', color: '#FF9100', community: 0, incoming: 2, outgoing: 1, weight: 7.0, x: 80, y: 200, summary: 'Launch first affiliate system.' },
  { id: 'task-workspace', label: 'Workspace Redesign', type: 'task', color: '#FFD600', community: 1, incoming: 3, outgoing: 1, weight: 8.8, x: 980, y: 200, summary: 'Cinematic 2.5D Agent Workspace redesign.' },
  { id: 'task-connector', label: 'Resolve Connector Drift', type: 'task', color: '#FF5252', community: 2, incoming: 2, outgoing: 1, weight: 7.6, x: 80, y: 460, summary: 'OpenClaw heartbeat drift blocker.' },
  { id: 'memory-system', label: 'System Memory', type: 'memory', color: '#A48BFF', community: 0, incoming: 2, outgoing: 4, weight: 8.0, x: 520, y: 540, summary: 'Durable AgentOS context.' },
  { id: 'memory-launch', label: 'Launch Memory', type: 'memory', color: '#FFD600', community: 1, incoming: 2, outgoing: 3, weight: 7.8, x: 880, y: 560, summary: 'Launch narrative and goal memory.' },
  { id: 'memory-cloud', label: 'Cloud Memory', type: 'memory', color: '#00E5FF', community: 2, incoming: 2, outgoing: 3, weight: 7.4, x: 200, y: 620, summary: 'Connector and cloud job memory.' },
  { id: 'alert-drift', label: 'Connector Drift', type: 'alert', color: '#FF5252', community: 2, incoming: 2, outgoing: 1, weight: 6.0, x: 380, y: 620, summary: 'OpenClaw connector heartbeat alert.' },
  { id: 'doc-prd', label: 'PRD', type: 'document', color: '#A48BFF', community: 0, incoming: 1, outgoing: 3, weight: 6.6, x: 380, y: 130, summary: 'System PRD document.' },
  { id: 'doc-repo', label: 'agentos-ui', type: 'repository', color: '#FFD600', community: 1, incoming: 1, outgoing: 3, weight: 7.2, x: 880, y: 320, summary: 'Operational React workspace.' },
]

export const GRAPH_EDGES: GraphEdge[] = [
  { id: 'e1', source: 'agentos', target: 'hermes', label: 'controlled-by', weight: 3, type: 'control' },
  { id: 'e2', source: 'hermes', target: 'claude', label: 'delegates', weight: 2.8, type: 'handoff' },
  { id: 'e3', source: 'hermes', target: 'opencode', label: 'delegates', weight: 2.4, type: 'handoff' },
  { id: 'e4', source: 'hermes', target: 'openclaw', label: 'monitors', weight: 2.1, type: 'control' },
  { id: 'e5', source: 'claude', target: 'opencode', label: 'reviews', weight: 2.6, type: 'ownership' },
  { id: 'e6', source: 'opencode', target: 'claude', label: 'reports', weight: 2.0, type: 'handoff' },
  { id: 'e7', source: 'openclaw', target: 'hermes', label: 'syncs', weight: 2.0, type: 'data' },
  { id: 'e8', source: 'hermes', target: 'wf-prompt', label: 'runs', weight: 2.5, type: 'execution' },
  { id: 'e9', source: 'claude', target: 'wf-code', label: 'runs', weight: 2.4, type: 'execution' },
  { id: 'e10', source: 'opencode', target: 'wf-code', label: 'edits', weight: 2.0, type: 'execution' },
  { id: 'e11', source: 'hermes', target: 'wf-graph', label: 'runs', weight: 2.6, type: 'execution' },
  { id: 'e12', source: 'openclaw', target: 'wf-connect', label: 'runs', weight: 2.3, type: 'execution' },
  { id: 'e13', source: 'wf-prompt', target: 'goal-launch', label: 'ships', weight: 2.4, type: 'goal' },
  { id: 'e14', source: 'wf-code', target: 'goal-ui', label: 'ships', weight: 2.4, type: 'goal' },
  { id: 'e15', source: 'wf-connect', target: 'goal-uptime', label: 'protects', weight: 2.2, type: 'goal' },
  { id: 'e16', source: 'claude', target: 'task-workspace', label: 'reviews', weight: 2.6, type: 'ownership' },
  { id: 'e17', source: 'opencode', target: 'task-workspace', label: 'implements', weight: 2.4, type: 'ownership' },
  { id: 'e18', source: 'hermes', target: 'task-affiliate', label: 'owns', weight: 1.9, type: 'ownership' },
  { id: 'e19', source: 'openclaw', target: 'task-connector', label: 'owns', weight: 2.3, type: 'ownership' },
  { id: 'e20', source: 'memory-system', target: 'agentos', label: 'context', weight: 2.0, type: 'memory' },
  { id: 'e21', source: 'memory-launch', target: 'wf-prompt', label: 'briefs', weight: 2.0, type: 'memory' },
  { id: 'e22', source: 'memory-cloud', target: 'wf-connect', label: 'indexes', weight: 1.8, type: 'memory' },
  { id: 'e23', source: 'alert-drift', target: 'openclaw', label: 'assigned', weight: 1.8, type: 'alert' },
  { id: 'e24', source: 'openclaw', target: 'alert-drift', label: 'raised', weight: 2.0, type: 'alert' },
  { id: 'e25', source: 'doc-prd', target: 'goal-launch', label: 'drives', weight: 1.9, type: 'document' },
  { id: 'e26', source: 'doc-prd', target: 'task-workspace', label: 'specs', weight: 2.0, type: 'document' },
  { id: 'e27', source: 'doc-repo', target: 'task-workspace', label: 'source', weight: 2.2, type: 'repository' },
  { id: 'e28', source: 'doc-repo', target: 'memory-system', label: 'writes', weight: 1.7, type: 'repository' },
  { id: 'e29', source: 'doc-repo', target: 'goal-ui', label: 'ships', weight: 2.3, type: 'goal' },
]

export const ANALYTICS_SERIES = {
  agentPerformance: [82, 86, 91, 87, 93, 90, 95, 92, 96, 94, 97, 95],
  workflowEfficiency: [68, 72, 70, 76, 81, 79, 84, 88, 86, 91, 89, 93],
  memoryGrowth: [1180, 1218, 1260, 1324, 1390, 1468, 1510, 1602, 1695, 1788, 1886, 2014],
  goalCompletion: [42, 45, 49, 52, 56, 61, 65, 67, 71, 74, 78, 81],
  tokenUsage: [540, 610, 575, 720, 810, 760, 890, 940, 1020, 980, 1110, 1190],
  graphGrowth: [72, 78, 86, 94, 103, 112, 124, 137, 151, 166, 181, 197],
}