import type { NavLink } from './demo-data'

export interface Plugin {
  id: string
  name: string
  description: string
  version: string
  author: string
  category: 'tool' | 'integration' | 'workflow' | 'ui' | 'utility' | 'model'
  status: 'enabled' | 'disabled' | 'error' | 'updating'
  icon: string
  iconColor: string
  tags: string[]
  dependencies: string[]
  capabilities: string[]
  permissions: string[]
  installDate: string
  lastUpdate: string
  size: string
  downloads: number
  rating: number
  repository: string
  changelog: string[]
}

export const PLUGINS: Plugin[] = [
  {
    id: 'graphify-cli',
    name: 'Graphify CLI',
    description: 'Knowledge graph extractor for codebases and documents. Supports TypeScript, Python, Rust, and Markdown.',
    version: '1.0.1',
    author: 'Nous Research',
    category: 'tool',
    status: 'enabled',
    icon: '◉',
    iconColor: '#f06292',
    tags: ['graph', 'extraction', 'cli'],
    dependencies: [],
    capabilities: ['code-parsing', 'entity-extraction', 'relationship-inference', 'graph-mutation'],
    permissions: ['filesystem.read', 'filesystem.write', 'process.exec'],
    installDate: '2026-06-15',
    lastUpdate: '2026-07-20',
    size: '12.4 MB',
    downloads: 1247,
    rating: 4.8,
    repository: 'github.com/nousresearch/graphify-cli',
    changelog: ['v1.0.1: Fixed memory leak in TypeScript parser', 'v1.0.0: Initial release with multi-language support'],
  },
  {
    id: 'telegram-bridge',
    name: 'Telegram Bridge',
    description: 'Bidirectional Telegram integration for agent notifications, commands, and file delivery.',
    version: '0.1.0',
    author: 'Hermes Team',
    category: 'integration',
    status: 'enabled',
    icon: '➤',
    iconColor: '#2ca5e0',
    tags: ['chat', 'notifications', 'bot'],
    dependencies: ['node-telegram-bot-api'],
    capabilities: ['send-message', 'receive-message', 'send-file', 'send-photo', 'inline-keyboards'],
    permissions: ['network.outbound', 'bot.token'],
    installDate: '2026-06-20',
    lastUpdate: '2026-07-10',
    size: '3.2 MB',
    downloads: 892,
    rating: 4.6,
    repository: 'github.com/hermes-ai/telegram-bridge',
    changelog: ['v0.1.0: Initial release with file delivery support'],
  },
  {
    id: 'discord-bridge',
    name: 'Discord Bridge',
    description: 'Discord integration for operator channels, slash commands, and rich embeds.',
    version: '0.5.2',
    author: 'Hermes Team',
    category: 'integration',
    status: 'enabled',
    icon: '◆',
    iconColor: '#5865f2',
    tags: ['chat', 'notifications', 'bot', 'slash-commands'],
    dependencies: ['discord.js'],
    capabilities: ['send-message', 'receive-message', 'slash-commands', 'rich-embeds', 'thread-support'],
    permissions: ['network.outbound', 'bot.token', 'guild.read'],
    installDate: '2026-06-18',
    lastUpdate: '2026-07-25',
    size: '4.8 MB',
    downloads: 1156,
    rating: 4.7,
    repository: 'github.com/hermes-ai/discord-bridge',
    changelog: ['v0.5.2: Fixed thread reply handling', 'v0.5.1: Added slash command autocomplete'],
  },
  {
    id: 'ollama-runtime',
    name: 'Ollama Runtime',
    description: 'Local LLM execution runtime. Manages model loading, inference, and model library.',
    version: '0.4.3',
    author: 'Ollama Team',
    category: 'model',
    status: 'enabled',
    icon: '⬢',
    iconColor: '#00e5ff',
    tags: ['llm', 'local', 'inference'],
    dependencies: [],
    capabilities: ['model-management', 'chat-completion', 'embeddings', 'model-pull', 'model-push'],
    permissions: ['network.localhost', 'filesystem.models', 'gpu.access'],
    installDate: '2026-06-01',
    lastUpdate: '2026-07-15',
    size: '45.2 MB',
    downloads: 3421,
    rating: 4.9,
    repository: 'github.com/ollama/ollama',
    changelog: ['v0.4.3: Improved GPU memory management', 'v0.4.2: Added multimodal model support'],
  },
  {
    id: 'claude-code',
    name: 'Claude Code CLI',
    description: 'Deep engineering agent. Code reviews, architecture analysis, refactoring, and long-horizon tasks.',
    version: '1.4.7',
    author: 'Anthropic',
    category: 'tool',
    status: 'enabled',
    icon: '⌘',
    iconColor: '#ff4d6d',
    tags: ['coding', 'review', 'architecture', 'analysis'],
    dependencies: ['@anthropic-ai/claude-code'],
    capabilities: ['code-review', 'architecture-analysis', 'refactoring', 'test-generation', 'git-operations'],
    permissions: ['filesystem.full', 'git.full', 'network.outbound', 'process.exec'],
    installDate: '2026-06-10',
    lastUpdate: '2026-07-28',
    size: '28.5 MB',
    downloads: 2134,
    rating: 4.8,
    repository: 'github.com/anthropics/claude-code',
    changelog: ['v1.4.7: Improved diff rendering', 'v1.4.6: Added test generation mode'],
  },
  {
    id: 'opencode',
    name: 'OpenCode',
    description: 'Fast implementation lane. TypeScript, Vite, file edits, commits, and diffs.',
    version: '0.9.1',
    author: 'OpenCode Team',
    category: 'tool',
    status: 'enabled',
    icon: '⌥',
    iconColor: '#ffb347',
    tags: ['coding', 'implementation', 'typescript', 'vite'],
    dependencies: [],
    capabilities: ['file-edits', 'commits', 'diffs', 'typescript', 'vite-integration', 'test-running'],
    permissions: ['filesystem.full', 'git.full', 'process.exec', 'network.localhost'],
    installDate: '2026-06-12',
    lastUpdate: '2026-07-22',
    size: '18.7 MB',
    downloads: 1876,
    rating: 4.5,
    repository: 'github.com/opencode-ai/opencode',
    changelog: ['v0.9.1: Fixed TypeScript config resolution', 'v0.9.0: Added Vite dev server integration'],
  },
  {
    id: 'openclaw',
    name: 'OpenClaw',
    description: 'Cloud execution surface. Connectors, automations, scheduled jobs, and runtime actions.',
    version: '1.2.1',
    author: 'Hermes Team',
    category: 'workflow',
    status: 'enabled',
    icon: '☁',
    iconColor: '#7c6cf5',
    tags: ['cloud', 'automation', 'scheduler', 'connectors'],
    dependencies: ['@hermes/openclaw-core'],
    capabilities: ['connector-management', 'job-scheduling', 'webhook-handling', 'automation-rules', 'secret-management'],
    permissions: ['network.outbound', 'secrets.read', 'schedule.manage', 'webhook.receive'],
    installDate: '2026-06-25',
    lastUpdate: '2026-07-30',
    size: '15.3 MB',
    downloads: 678,
    rating: 4.3,
    repository: 'github.com/hermes-ai/openclaw',
    changelog: ['v1.2.1: Fixed connector heartbeat drift', 'v1.2.0: Added retry policy configuration'],
  },
  {
    id: 'graphify-update',
    name: 'Graphify Update',
    description: 'Re-extract code graph on demand. Triggered manually or on git push.',
    version: '1.0.1',
    author: 'Nous Research',
    category: 'utility',
    status: 'enabled',
    icon: '↻',
    iconColor: '#22d97a',
    tags: ['graph', 'update', 'automation'],
    dependencies: ['graphify-cli'],
    capabilities: ['incremental-extraction', 'git-hooks', 'scheduled-runs', 'diff-aware'],
    permissions: ['filesystem.read', 'git.read', 'schedule.manage'],
    installDate: '2026-07-01',
    lastUpdate: '2026-07-18',
    size: '2.1 MB',
    downloads: 445,
    rating: 4.4,
    repository: 'github.com/nousresearch/graphify-update',
    changelog: ['v1.0.1: Added diff-aware extraction', 'v1.0.0: Initial release'],
  },
  {
    id: 'github-integration',
    name: 'GitHub Integration',
    description: 'GitHub API integration for issues, PRs, releases, and repository management.',
    version: '0.3.0',
    author: 'Hermes Team',
    category: 'integration',
    status: 'enabled',
    icon: '⌘',
    iconColor: '#22d97a',
    tags: ['github', 'issues', 'prs', 'releases'],
    dependencies: ['@octokit/rest'],
    capabilities: ['issue-management', 'pr-review', 'release-management', 'repo-stats', 'webhook-handling'],
    permissions: ['network.outbound', 'github.token', 'repo.read', 'repo.write'],
    installDate: '2026-07-05',
    lastUpdate: '2026-07-20',
    size: '5.6 MB',
    downloads: 723,
    rating: 4.6,
    repository: 'github.com/hermes-ai/github-integration',
    changelog: ['v0.3.0: Added PR review automation', 'v0.2.1: Fixed webhook signature verification'],
  },
  {
    id: 'linear-integration',
    name: 'Linear Integration',
    description: 'Linear issue tracker integration for task sync, project views, and sprint management.',
    version: '0.2.1',
    author: 'Hermes Team',
    category: 'integration',
    status: 'disabled',
    icon: '◈',
    iconColor: '#ffb347',
    tags: ['linear', 'issues', 'sprints', 'projects'],
    dependencies: ['@linear/sdk'],
    capabilities: ['issue-sync', 'project-views', 'sprint-management', 'cycle-tracking'],
    permissions: ['network.outbound', 'linear.token', 'workspace.read'],
    installDate: '2026-07-10',
    lastUpdate: '2026-07-10',
    size: '3.8 MB',
    downloads: 312,
    rating: 4.2,
    repository: 'github.com/hermes-ai/linear-integration',
    changelog: ['v0.2.1: Fixed cycle date parsing', 'v0.2.0: Added sprint management'],
  },
  {
    id: 'notion-sync',
    name: 'Notion Sync',
    description: 'Bidirectional Notion workspace synchronization for docs, databases, and pages.',
    version: '0.1.5',
    author: 'Hermes Team',
    category: 'integration',
    status: 'disabled',
    icon: '◧',
    iconColor: '#00e5ff',
    tags: ['notion', 'sync', 'docs', 'databases'],
    dependencies: ['@notionhq/client'],
    capabilities: ['page-sync', 'database-sync', 'block-operations', 'search'],
    permissions: ['network.outbound', 'notion.token', 'workspace.read', 'workspace.write'],
    installDate: '2026-07-12',
    lastUpdate: '2026-07-12',
    size: '4.2 MB',
    downloads: 287,
    rating: 4.0,
    repository: 'github.com/hermes-ai/notion-sync',
    changelog: ['v0.1.5: Fixed database property mapping', 'v0.1.4: Added block-level sync'],
  },
  {
    id: 'slack-bridge',
    name: 'Slack Bridge',
    description: 'Slack integration for channel messages, DMs, and slash commands.',
    version: '0.4.0',
    author: 'Hermes Team',
    category: 'integration',
    status: 'error',
    icon: '⊕',
    iconColor: '#4A154B',
    tags: ['slack', 'chat', 'notifications'],
    dependencies: ['@slack/bolt'],
    capabilities: ['send-message', 'receive-message', 'slash-commands', 'modal-views', 'block-kit'],
    permissions: ['network.outbound', 'slack.token', 'channels.read', 'chat.write'],
    installDate: '2026-07-15',
    lastUpdate: '2026-07-15',
    size: '6.1 MB',
    downloads: 198,
    rating: 3.8,
    repository: 'github.com/hermes-ai/slack-bridge',
    changelog: ['v0.4.0: Initial release with block kit support'],
  },
  {
    id: 'vscode-extension',
    name: 'VS Code Extension',
    description: 'VS Code extension for Hermes AgentOS. Inline chat, code actions, and workspace sync.',
    version: '0.8.0',
    author: 'Hermes Team',
    category: 'ui',
    status: 'enabled',
    icon: '◬',
    iconColor: '#007ACC',
    tags: ['vscode', 'editor', 'ide', 'integration'],
    dependencies: [],
    capabilities: ['inline-chat', 'code-actions', 'workspace-sync', 'diagnostics', 'terminal-integration'],
    permissions: ['filesystem.workspace', 'vscode.api', 'terminal.access'],
    installDate: '2026-07-01',
    lastUpdate: '2026-07-25',
    size: '8.4 MB',
    downloads: 1567,
    rating: 4.7,
    repository: 'github.com/hermes-ai/vscode-extension',
    changelog: ['v0.8.0: Added terminal integration', 'v0.7.2: Fixed workspace sync conflicts'],
  },
]

export interface PluginMarketplaceEntry {
  id: string
  name: string
  description: string
  version: string
  author: string
  category: Plugin['category']
  icon: string
  iconColor: string
  tags: string[]
  downloads: number
  rating: number
  verified: boolean
  price: 'free' | 'paid'
}

export const PLUGIN_MARKETPLACE: PluginMarketplaceEntry[] = [
  {
    id: 'jira-integration',
    name: 'Jira Integration',
    description: 'Jira issue tracker sync with sprint boards and custom fields.',
    version: '0.3.2',
    author: 'Community',
    category: 'integration',
    icon: '◈',
    iconColor: '#0052CC',
    tags: ['jira', 'issues', 'sprints', 'agile'],
    downloads: 445,
    rating: 4.3,
    verified: true,
    price: 'free',
  },
  {
    id: 'datadog-monitoring',
    name: 'Datadog Monitoring',
    description: 'Datadog APM and infrastructure monitoring integration.',
    version: '1.1.0',
    author: 'Datadog',
    category: 'integration',
    icon: '◉',
    iconColor: '#632CA6',
    tags: ['datadog', 'apm', 'metrics', 'logs'],
    downloads: 234,
    rating: 4.5,
    verified: true,
    price: 'paid',
  },
  {
    id: 'postgres-connector',
    name: 'PostgreSQL Connector',
    description: 'Direct PostgreSQL database connector for queries and migrations.',
    version: '0.5.1',
    author: 'Community',
    category: 'tool',
    icon: '⬢',
    iconColor: '#336791',
    tags: ['postgres', 'database', 'sql', 'migrations'],
    downloads: 567,
    rating: 4.4,
    verified: true,
    price: 'free',
  },
  {
    id: 'redis-cache',
    name: 'Redis Cache',
    description: 'Redis caching layer with automatic invalidation and TTL management.',
    version: '0.2.3',
    author: 'Community',
    category: 'utility',
    icon: '◉',
    iconColor: '#DC382D',
    tags: ['redis', 'cache', 'performance', 'ttl'],
    downloads: 389,
    rating: 4.2,
    verified: true,
    price: 'free',
  },
  {
    id: 'sentry-error-tracking',
    name: 'Sentry Error Tracking',
    description: 'Sentry integration for error monitoring, performance tracing, and release tracking.',
    version: '1.0.0',
    author: 'Sentry',
    category: 'integration',
    icon: '⚠',
    iconColor: '#362D59',
    tags: ['sentry', 'errors', 'performance', 'releases'],
    downloads: 412,
    rating: 4.6,
    verified: true,
    price: 'paid',
  },
  {
    id: 'figma-design-sync',
    name: 'Figma Design Sync',
    description: 'Figma design system sync for component libraries and design tokens.',
    version: '0.1.2',
    author: 'Community',
    category: 'integration',
    icon: '◧',
    iconColor: '#F24E1E',
    tags: ['figma', 'design', 'components', 'tokens'],
    downloads: 178,
    rating: 4.1,
    verified: false,
    price: 'free',
  },
  {
    id: 'aws-deploy',
    name: 'AWS Deploy',
    description: 'AWS deployment automation for Lambda, ECS, and CloudFormation.',
    version: '0.4.0',
    author: 'Community',
    category: 'workflow',
    icon: '☁',
    iconColor: '#FF9900',
    tags: ['aws', 'deploy', 'lambda', 'ecs', 'cloudformation'],
    downloads: 289,
    rating: 4.0,
    verified: true,
    price: 'free',
  },
  {
    id: 'vercel-deploy',
    name: 'Vercel Deploy',
    description: 'Vercel deployment integration for Next.js and static sites.',
    version: '0.3.1',
    author: 'Vercel',
    category: 'workflow',
    icon: '◬',
    iconColor: '#000000',
    tags: ['vercel', 'deploy', 'nextjs', 'edge'],
    downloads: 523,
    rating: 4.7,
    verified: true,
    price: 'free',
  },
]

export interface PluginPermission {
  name: string
  description: string
  risk: 'low' | 'medium' | 'high'
  plugins: string[]
}

export const PLUGIN_PERMISSIONS: PluginPermission[] = [
  { name: 'filesystem.read', description: 'Read files from the workspace', risk: 'low', plugins: ['graphify-cli', 'opencode', 'github-integration', 'postgres-connector'] },
  { name: 'filesystem.write', description: 'Write files to the workspace', risk: 'medium', plugins: ['graphify-cli', 'opencode', 'graphify-update', 'notion-sync'] },
  { name: 'filesystem.full', description: 'Full filesystem access', risk: 'high', plugins: ['claude-code', 'opencode', 'vscode-extension'] },
  { name: 'git.read', description: 'Read git repository information', risk: 'low', plugins: ['claude-code', 'opencode', 'graphify-update', 'github-integration'] },
  { name: 'git.full', description: 'Full git access (commit, push, branch)', risk: 'high', plugins: ['claude-code', 'opencode'] },
  { name: 'network.localhost', description: 'Access localhost services', risk: 'low', plugins: ['ollama-runtime', 'opencode'] },
  { name: 'network.outbound', description: 'Make outbound network requests', risk: 'medium', plugins: ['telegram-bridge', 'discord-bridge', 'openclaw', 'github-integration', 'linear-integration', 'notion-sync', 'slack-bridge', 'jira-integration', 'datadog-monitoring', 'sentry-error-tracking', 'aws-deploy', 'vercel-deploy'] },
  { name: 'process.exec', description: 'Execute shell commands', risk: 'high', plugins: ['graphify-cli', 'claude-code', 'opencode'] },
  { name: 'gpu.access', description: 'Access GPU for inference', risk: 'medium', plugins: ['ollama-runtime'] },
  { name: 'secrets.read', description: 'Read secrets from vault', risk: 'high', plugins: ['openclaw', 'aws-deploy', 'vercel-deploy'] },
  { name: 'schedule.manage', description: 'Manage scheduled jobs', risk: 'medium', plugins: ['openclaw', 'graphify-update'] },
  { name: 'webhook.receive', description: 'Receive incoming webhooks', risk: 'medium', plugins: ['openclaw', 'github-integration', 'linear-integration', 'slack-bridge'] },
  { name: 'vscode.api', description: 'Access VS Code extension API', risk: 'medium', plugins: ['vscode-extension'] },
  { name: 'terminal.access', description: 'Access integrated terminal', risk: 'high', plugins: ['vscode-extension'] },
]

export const PLUGIN_NAV_LINKS: NavLink[] = [
  { id: 'plugins-overview', label: 'Overview', icon: '◎', group: 'self' },
  { id: 'plugins-installed', label: 'Installed', icon: '◧', group: 'self' },
  { id: 'plugins-marketplace', label: 'Marketplace', icon: '⊕', group: 'self' },
  { id: 'plugins-permissions', label: 'Permissions', icon: '⚠', group: 'self' },
  { id: 'plugins-settings', label: 'Settings', icon: '⚙', group: 'self' },
]