import type { NavLink } from './demo-data'

export interface Skill {
  id: string
  name: string
  description: string
  version: string
  author: string
  category: 'automation' | 'coding' | 'analysis' | 'communication' | 'data' | 'utility' | 'integration'
  status: 'enabled' | 'disabled' | 'error' | 'draft'
  icon: string
  iconColor: string
  tags: string[]
  triggers: string[]
  actions: string[]
  schedule?: string
  lastRun?: string
  nextRun?: string
  runCount: number
  successRate: number
  avgDuration: string
  installDate: string
  lastUpdate: string
  size: string
  repository: string
  manifest: SkillManifest
}

export interface SkillManifest {
  name: string
  version: string
  description: string
  author: string
  license: string
  homepage: string
  keywords: string[]
  permissions: string[]
  dependencies: Record<string, string>
  entryPoint: string
  configSchema: Record<string, any>
  triggers: SkillTrigger[]
  actions: SkillAction[]
}

export interface SkillTrigger {
  type: 'schedule' | 'event' | 'webhook' | 'manual' | 'condition'
  config: Record<string, any>
}

export interface SkillAction {
  name: string
  description: string
  params: Record<string, any>
  returns: string
}

export const SKILLS: Skill[] = [
  {
    id: 'graph-memory-sync',
    name: 'Graph Memory Sync',
    description: 'Read logs, extract entities, update the live knowledge graph. Runs continuously to keep the graph current.',
    version: '1.2.0',
    author: 'Hermes Team',
    category: 'data',
    status: 'enabled',
    icon: '◉',
    iconColor: '#7c6cf5',
    tags: ['graph', 'memory', 'sync', 'continuous'],
    triggers: ['schedule:*/5 * * * *', 'event:log.write'],
    actions: ['read-logs', 'extract-entities', 'update-graph', 'cluster-communities'],
    schedule: '*/5 * * * *',
    lastRun: '2m ago',
    nextRun: '3m',
    runCount: 421,
    successRate: 99.8,
    avgDuration: '48s',
    installDate: '2026-06-15',
    lastUpdate: '2026-07-20',
    size: '2.4 MB',
    repository: 'github.com/hermes-ai/graph-memory-sync',
    manifest: {
      name: 'graph-memory-sync',
      version: '1.2.0',
      description: 'Continuous knowledge graph synchronization from agent logs',
      author: 'Hermes Team',
      license: 'MIT',
      homepage: 'github.com/hermes-ai/graph-memory-sync',
      keywords: ['graph', 'memory', 'sync', 'continuous'],
      permissions: ['logs.read', 'graph.write', 'schedule.manage'],
      dependencies: { 'graphify-core': '^1.0.0' },
      entryPoint: 'dist/index.js',
      configSchema: { syncInterval: { type: 'number', default: 300 }, batchSize: { type: 'number', default: 100 } },
      triggers: [{ type: 'schedule', config: { cron: '*/5 * * * *' } }, { type: 'event', config: { event: 'log.write' } }],
      actions: [
        { name: 'read-logs', description: 'Read recent agent logs', params: { limit: 'number' }, returns: 'LogEntry[]' },
        { name: 'extract-entities', description: 'Extract entities from text', params: { text: 'string' }, returns: 'Entity[]' },
        { name: 'update-graph', description: 'Mutate knowledge graph', params: { entities: 'Entity[]', relations: 'Relation[]' }, returns: 'MutationResult' },
        { name: 'cluster-communities', description: 'Run community detection', params: { algorithm: 'louvain|leiden' }, returns: 'Community[]' },
      ],
    },
  },
  {
    id: 'prompt-to-production',
    name: 'Prompt to Production',
    description: 'End-to-end pipeline: prompt → plan → implement → verify → deploy. Multi-agent workflow orchestration.',
    version: '2.1.0',
    author: 'Hermes Team',
    category: 'automation',
    status: 'enabled',
    icon: '⌘',
    iconColor: '#d946ef',
    tags: ['workflow', 'pipeline', 'multi-agent', 'deployment'],
    triggers: ['manual', 'webhook:github.pr'],
    actions: ['route-to-claude', 'plan-implementation', 'implement-with-opencode', 'verify-build', 'deploy-with-openclaw'],
    lastRun: '1h ago',
    nextRun: 'manual',
    runCount: 128,
    successRate: 97.7,
    avgDuration: '3m 42s',
    installDate: '2026-06-20',
    lastUpdate: '2026-07-25',
    size: '3.1 MB',
    repository: 'github.com/hermes-ai/prompt-to-production',
    manifest: {
      name: 'prompt-to-production',
      version: '2.1.0',
      description: 'End-to-end prompt-to-production pipeline',
      author: 'Hermes Team',
      license: 'MIT',
      homepage: 'github.com/hermes-ai/prompt-to-production',
      keywords: ['workflow', 'pipeline', 'multi-agent', 'deployment'],
      permissions: ['agents.invoke', 'git.full', 'deploy.manage', 'webhook.receive'],
      dependencies: { 'hermes-workflow-engine': '^1.0.0' },
      entryPoint: 'dist/index.js',
      configSchema: { autoDeploy: { type: 'boolean', default: false }, requireApproval: { type: 'boolean', default: true } },
      triggers: [{ type: 'manual', config: {} }, { type: 'webhook', config: { path: '/github/pr' } }],
      actions: [
        { name: 'route-to-claude', description: 'Send prompt to Claude for planning', params: { prompt: 'string' }, returns: 'Plan' },
        { name: 'plan-implementation', description: 'Generate implementation plan', params: { spec: 'string' }, returns: 'Task[]' },
        { name: 'implement-with-opencode', description: 'Execute implementation', params: { tasks: 'Task[]' }, returns: 'Diff[]' },
        { name: 'verify-build', description: 'Typecheck, build, test', params: { diff: 'Diff' }, returns: 'VerificationResult' },
        { name: 'deploy-with-openclaw', description: 'Deploy to production', params: { artifact: 'string' }, returns: 'DeploymentResult' },
      ],
    },
  },
  {
    id: 'code-change-verification',
    name: 'Code Change Verification',
    description: 'Implement, typecheck, build, review diff. Multi-agent loop for quality assurance.',
    version: '1.0.3',
    author: 'Claude Code Team',
    category: 'coding',
    status: 'enabled',
    icon: '⌘',
    iconColor: '#ff4d6d',
    tags: ['verification', 'typecheck', 'build', 'review', 'multi-agent'],
    triggers: ['event:git.push', 'manual'],
    actions: ['implement', 'typecheck', 'build', 'review-diff'],
    lastRun: '45m ago',
    nextRun: 'on push',
    runCount: 64,
    successRate: 92.2,
    avgDuration: '11m 12s',
    installDate: '2026-06-25',
    lastUpdate: '2026-07-18',
    size: '1.8 MB',
    repository: 'github.com/anthropics/code-change-verification',
    manifest: {
      name: 'code-change-verification',
      version: '1.0.3',
      description: 'Multi-agent code change verification loop',
      author: 'Claude Code Team',
      license: 'MIT',
      homepage: 'github.com/anthropics/code-change-verification',
      keywords: ['verification', 'typecheck', 'build', 'review', 'multi-agent'],
      permissions: ['git.read', 'process.exec', 'agents.invoke'],
      dependencies: { 'typescript': '^5.0.0', 'vitest': '^1.0.0' },
      entryPoint: 'dist/index.js',
      configSchema: { strictMode: { type: 'boolean', default: true }, runTests: { type: 'boolean', default: true } },
      triggers: [{ type: 'event', config: { event: 'git.push' } }, { type: 'manual', config: {} }],
      actions: [
        { name: 'implement', description: 'Implement changes', params: { spec: 'string' }, returns: 'Diff' },
        { name: 'typecheck', description: 'Run TypeScript typecheck', params: {}, returns: 'TypeCheckResult' },
        { name: 'build', description: 'Run production build', params: {}, returns: 'BuildResult' },
        { name: 'review-diff', description: 'Architecture review of diff', params: { diff: 'Diff' }, returns: 'ReviewResult' },
      ],
    },
  },
  {
    id: 'connector-health-sweep',
    name: 'Connector Health Sweep',
    description: 'Ping every connector, classify failures, open alerts. Maintains OpenClaw connector uptime.',
    version: '1.1.2',
    author: 'Hermes Team',
    category: 'automation',
    status: 'enabled',
    icon: '☁',
    iconColor: '#00e5ff',
    tags: ['connectors', 'health', 'monitoring', 'alerts', 'ops'],
    triggers: ['schedule:0 */6 * * *', 'manual'],
    actions: ['ping-connector', 'collect-latency', 'classify-failures', 'open-alert'],
    schedule: '0 */6 * * *',
    lastRun: '2h ago',
    nextRun: '4h',
    runCount: 87,
    successRate: 89.7,
    avgDuration: '7m 03s',
    installDate: '2026-07-01',
    lastUpdate: '2026-07-28',
    size: '2.1 MB',
    repository: 'github.com/hermes-ai/connector-health-sweep',
    manifest: {
      name: 'connector-health-sweep',
      version: '1.1.2',
      description: 'Periodic connector health monitoring and alerting',
      author: 'Hermes Team',
      license: 'MIT',
      homepage: 'github.com/hermes-ai/connector-health-sweep',
      keywords: ['connectors', 'health', 'monitoring', 'alerts', 'ops'],
      permissions: ['connectors.read', 'alerts.write', 'schedule.manage'],
      dependencies: { 'openclaw-client': '^1.2.0' },
      entryPoint: 'dist/index.js',
      configSchema: { intervalHours: { type: 'number', default: 6 }, timeoutMs: { type: 'number', default: 5000 }, alertThreshold: { type: 'number', default: 3 } },
      triggers: [{ type: 'schedule', config: { cron: '0 */6 * * *' } }, { type: 'manual', config: {} }],
      actions: [
        { name: 'ping-connector', description: 'Health check a connector', params: { connectorId: 'string' }, returns: 'HealthResult' },
        { name: 'collect-latency', description: 'Measure connector latency', params: { connectorId: 'string' }, returns: 'LatencyResult' },
        { name: 'classify-failures', description: 'Classify failure types', params: { results: 'HealthResult[]' }, returns: 'FailureClassification[]' },
        { name: 'open-alert', description: 'Create alert for failed connectors', params: { failures: 'FailureClassification[]' }, returns: 'Alert[]' },
      ],
    },
  },
  {
    id: 'launch-sprint-rollup',
    name: 'Launch Sprint Rollup',
    description: 'Read tasks, map goals, summarize blockers, write memory. Weekly sprint summary generation.',
    version: '1.0.0',
    author: 'Hermes Team',
    category: 'analysis',
    status: 'enabled',
    icon: '◈',
    iconColor: '#f06292',
    tags: ['sprint', 'rollup', 'summary', 'goals', 'weekly'],
    triggers: ['schedule:0 9 * * 1', 'manual'],
    actions: ['read-tasks', 'map-goals', 'summarize-blockers', 'write-memory'],
    schedule: '0 9 * * 1',
    lastRun: '3d ago',
    nextRun: '4d',
    runCount: 215,
    successRate: 99.1,
    avgDuration: '2m 18s',
    installDate: '2026-06-10',
    lastUpdate: '2026-07-10',
    size: '1.5 MB',
    repository: 'github.com/hermes-ai/launch-sprint-rollup',
    manifest: {
      name: 'launch-sprint-rollup',
      version: '1.0.0',
      description: 'Weekly sprint rollup and goal tracking',
      author: 'Hermes Team',
      license: 'MIT',
      homepage: 'github.com/hermes-ai/launch-sprint-rollup',
      keywords: ['sprint', 'rollup', 'summary', 'goals', 'weekly'],
      permissions: ['tasks.read', 'goals.read', 'memory.write', 'schedule.manage'],
      dependencies: { 'hermes-memory': '^1.0.0' },
      entryPoint: 'dist/index.js',
      configSchema: { dayOfWeek: { type: 'number', default: 1 }, hour: { type: 'number', default: 9 }, includeBlockers: { type: 'boolean', default: true } },
      triggers: [{ type: 'schedule', config: { cron: '0 9 * * 1' } }, { type: 'manual', config: {} }],
      actions: [
        { name: 'read-tasks', description: 'Fetch sprint tasks', params: { sprintId: 'string' }, returns: 'Task[]' },
        { name: 'map-goals', description: 'Map tasks to goals', params: { tasks: 'Task[]' }, returns: 'GoalMapping[]' },
        { name: 'summarize-blockers', description: 'Identify and summarize blockers', params: { tasks: 'Task[]' }, returns: 'BlockerSummary[]' },
        { name: 'write-memory', description: 'Write rollup to memory', params: { content: 'string' }, returns: 'MemoryEntry' },
      ],
    },
  },
  {
    id: 'daily-digest',
    name: 'Daily Digest',
    description: 'Generate and deliver daily summary via Telegram and Discord. Includes goals, alerts, and metrics.',
    version: '0.9.1',
    author: 'Hermes Team',
    category: 'communication',
    status: 'enabled',
    icon: '◴',
    iconColor: '#22d97a',
    tags: ['digest', 'daily', 'telegram', 'discord', 'summary'],
    triggers: ['schedule:0 7 * * *'],
    actions: ['collect-metrics', 'format-digest', 'send-telegram', 'send-discord'],
    schedule: '0 7 * * *',
    lastRun: '18h ago',
    nextRun: '6h',
    runCount: 67,
    successRate: 98.5,
    avgDuration: '15s',
    installDate: '2026-07-05',
    lastUpdate: '2026-07-20',
    size: '1.2 MB',
    repository: 'github.com/hermes-ai/daily-digest',
    manifest: {
      name: 'daily-digest',
      version: '0.9.1',
      description: 'Daily summary delivery via chat channels',
      author: 'Hermes Team',
      license: 'MIT',
      homepage: 'github.com/hermes-ai/daily-digest',
      keywords: ['digest', 'daily', 'telegram', 'discord', 'summary'],
      permissions: ['telegram.send', 'discord.send', 'metrics.read', 'schedule.manage'],
      dependencies: { 'telegram-bridge': '^0.1.0', 'discord-bridge': '^0.5.0' },
      entryPoint: 'dist/index.js',
      configSchema: { hour: { type: 'number', default: 7 }, channels: { type: 'array', default: ['telegram', 'discord'] }, includeMetrics: { type: 'boolean', default: true } },
      triggers: [{ type: 'schedule', config: { cron: '0 7 * * *' } }],
      actions: [
        { name: 'collect-metrics', description: 'Gather daily metrics', params: {}, returns: 'Metrics' },
        { name: 'format-digest', description: 'Format digest message', params: { metrics: 'Metrics' }, returns: 'string' },
        { name: 'send-telegram', description: 'Send to Telegram', params: { message: 'string' }, returns: 'SendResult' },
        { name: 'send-discord', description: 'Send to Discord', params: { message: 'string' }, returns: 'SendResult' },
      ],
    },
  },
  {
    id: 'graphify-update',
    name: 'Graphify Update',
    description: 'Re-extract code graph on demand. Triggered manually or on git push. Incremental extraction with diff awareness.',
    version: '1.0.1',
    author: 'Nous Research',
    category: 'utility',
    status: 'enabled',
    icon: '↻',
    iconColor: '#22d97a',
    tags: ['graph', 'update', 'extraction', 'incremental', 'git'],
    triggers: ['event:git.push', 'manual', 'schedule:0 2 * * *'],
    actions: ['detect-changes', 'incremental-extract', 'update-graph', 'notify-complete'],
    schedule: '0 2 * * *',
    lastRun: '6h ago',
    nextRun: '20h',
    runCount: 89,
    successRate: 95.5,
    avgDuration: '45s',
    installDate: '2026-07-01',
    lastUpdate: '2026-07-18',
    size: '2.1 MB',
    repository: 'github.com/nousresearch/graphify-update',
    manifest: {
      name: 'graphify-update',
      version: '1.0.1',
      description: 'Incremental code graph extraction',
      author: 'Nous Research',
      license: 'MIT',
      homepage: 'github.com/nousresearch/graphify-update',
      keywords: ['graph', 'update', 'extraction', 'incremental', 'git'],
      permissions: ['filesystem.read', 'git.read', 'graph.write', 'schedule.manage'],
      dependencies: { 'graphify-cli': '^1.0.0' },
      entryPoint: 'dist/index.js',
      configSchema: { incremental: { type: 'boolean', default: true }, fullRescanDaily: { type: 'boolean', default: true } },
      triggers: [{ type: 'event', config: { event: 'git.push' } }, { type: 'manual', config: {} }, { type: 'schedule', config: { cron: '0 2 * * *' } }],
      actions: [
        { name: 'detect-changes', description: 'Detect changed files since last run', params: { since: 'string' }, returns: 'string[]' },
        { name: 'incremental-extract', description: 'Extract graph from changed files', params: { files: 'string[]' }, returns: 'GraphDelta' },
        { name: 'update-graph', description: 'Apply delta to knowledge graph', params: { delta: 'GraphDelta' }, returns: 'UpdateResult' },
        { name: 'notify-complete', description: 'Send completion notification', params: { result: 'UpdateResult' }, returns: 'void' },
      ],
    },
  },
  {
    id: 'vault-compression',
    name: 'Vault Compression',
    description: 'Compress and partition Obsidian vault in IndexedDB. LZ4 compression with chunked storage.',
    version: '0.8.0',
    author: 'Hermes Team',
    category: 'utility',
    status: 'enabled',
    icon: '◧',
    iconColor: '#ffb347',
    tags: ['vault', 'compression', 'indexeddb', 'performance', 'storage'],
    triggers: ['schedule:0 3 * * 0', 'manual'],
    actions: ['analyze-vault', 'compress-chunks', 'write-indexeddb', 'verify-integrity'],
    schedule: '0 3 * * 0',
    lastRun: '1w ago',
    nextRun: '6d',
    runCount: 12,
    successRate: 100,
    avgDuration: '8m 30s',
    installDate: '2026-06-28',
    lastUpdate: '2026-07-20',
    size: '3.4 MB',
    repository: 'github.com/hermes-ai/vault-compression',
    manifest: {
      name: 'vault-compression',
      version: '0.8.0',
      description: 'Vault compression and IndexedDB partitioning',
      author: 'Hermes Team',
      license: 'MIT',
      homepage: 'github.com/hermes-ai/vault-compression',
      keywords: ['vault', 'compression', 'indexeddb', 'performance', 'storage'],
      permissions: ['filesystem.read', 'filesystem.write', 'indexeddb.write', 'schedule.manage'],
      dependencies: { 'lz4': '^1.0.0', 'idb': '^7.0.0' },
      entryPoint: 'dist/index.js',
      configSchema: { chunkSize: { type: 'number', default: 1024 * 1024 }, compressionLevel: { type: 'number', default: 9 }, runWeekly: { type: 'boolean', default: true } },
      triggers: [{ type: 'schedule', config: { cron: '0 3 * * 0' } }, { type: 'manual', config: {} }],
      actions: [
        { name: 'analyze-vault', description: 'Analyze vault structure and size', params: {}, returns: 'VaultAnalysis' },
        { name: 'compress-chunks', description: 'Compress vault into chunks', params: { files: 'FileEntry[]' }, returns: 'CompressedChunk[]' },
        { name: 'write-indexeddb', description: 'Write chunks to IndexedDB', params: { chunks: 'CompressedChunk[]' }, returns: 'WriteResult' },
        { name: 'verify-integrity', description: 'Verify compression integrity', params: { chunks: 'CompressedChunk[]' }, returns: 'VerificationResult' },
      ],
    },
  },
  {
    id: 'omi-transcript-cleanup',
    name: 'Omi Transcript Cleanup',
    description: 'Heuristic rules for cleaning Omi voice transcripts. Removes filler words, fixes punctuation, segments by speaker.',
    version: '0.6.2',
    author: 'Hermes Team',
    category: 'data',
    status: 'enabled',
    icon: '◉',
    iconColor: '#00e5ff',
    tags: ['omi', 'transcript', 'cleanup', 'nlp', 'heuristics'],
    triggers: ['event:omi.capture', 'schedule:*/30 * * * *'],
    actions: ['fetch-transcript', 'remove-fillers', 'fix-punctuation', 'segment-speakers', 'save-cleaned'],
    schedule: '*/30 * * * *',
    lastRun: '15m ago',
    nextRun: '15m',
    runCount: 234,
    successRate: 97.0,
    avgDuration: '12s',
    installDate: '2026-07-01',
    lastUpdate: '2026-07-18',
    size: '1.8 MB',
    repository: 'github.com/hermes-ai/omi-transcript-cleanup',
    manifest: {
      name: 'omi-transcript-cleanup',
      version: '0.6.2',
      description: 'Omi voice transcript cleaning pipeline',
      author: 'Hermes Team',
      license: 'MIT',
      homepage: 'github.com/hermes-ai/omi-transcript-cleanup',
      keywords: ['omi', 'transcript', 'cleanup', 'nlp', 'heuristics'],
      permissions: ['omi.read', 'memory.write', 'schedule.manage'],
      dependencies: { 'compromise': '^14.0.0' },
      entryPoint: 'dist/index.js',
      configSchema: { fillerWords: { type: 'array', default: ['um', 'uh', 'like', 'you know'] }, minSegmentLength: { type: 'number', default: 5 } },
      triggers: [{ type: 'event', config: { event: 'omi.capture' } }, { type: 'schedule', config: { cron: '*/30 * * * *' } }],
      actions: [
        { name: 'fetch-transcript', description: 'Get raw transcript from Omi', params: { captureId: 'string' }, returns: 'Transcript' },
        { name: 'remove-fillers', description: 'Remove filler words', params: { text: 'string' }, returns: 'string' },
        { name: 'fix-punctuation', description: 'Fix punctuation and capitalization', params: { text: 'string' }, returns: 'string' },
        { name: 'segment-speakers', description: 'Segment by speaker', params: { text: 'string' }, returns: 'SpeakerSegment[]' },
        { name: 'save-cleaned', description: 'Save cleaned transcript', params: { segments: 'SpeakerSegment[]' }, returns: 'MemoryEntry' },
      ],
    },
  },
  {
    id: 'github-pr-review',
    name: 'GitHub PR Review',
    description: 'Automated PR review with architecture analysis, security scan, and style checking.',
    version: '0.4.0',
    author: 'Community',
    category: 'coding',
    status: 'disabled',
    icon: '⌘',
    iconColor: '#22d97a',
    tags: ['github', 'pr', 'review', 'security', 'automation'],
    triggers: ['webhook:github.pr'],
    actions: ['fetch-pr', 'analyze-diff', 'security-scan', 'style-check', 'post-review'],
    lastRun: 'never',
    nextRun: 'on PR',
    runCount: 0,
    successRate: 0,
    avgDuration: '0s',
    installDate: '2026-07-15',
    lastUpdate: '2026-07-15',
    size: '2.6 MB',
    repository: 'github.com/community/github-pr-review',
    manifest: {
      name: 'github-pr-review',
      version: '0.4.0',
      description: 'Automated GitHub PR review',
      author: 'Community',
      license: 'MIT',
      homepage: 'github.com/community/github-pr-review',
      keywords: ['github', 'pr', 'review', 'security', 'automation'],
      permissions: ['github.token', 'repo.read', 'repo.write', 'webhook.receive'],
      dependencies: { '@octokit/rest': '^19.0.0', 'eslint': '^8.0.0' },
      entryPoint: 'dist/index.js',
      configSchema: { autoApprove: { type: 'boolean', default: false }, requireTests: { type: 'boolean', default: true } },
      triggers: [{ type: 'webhook', config: { path: '/github/pr' } }],
      actions: [
        { name: 'fetch-pr', description: 'Fetch PR details and diff', params: { prNumber: 'number' }, returns: 'PRData' },
        { name: 'analyze-diff', description: 'Analyze code changes', params: { diff: 'string' }, returns: 'Analysis' },
        { name: 'security-scan', description: 'Run security scan', params: { diff: 'string' }, returns: 'SecurityIssues[]' },
        { name: 'style-check', description: 'Check code style', params: { diff: 'string' }, returns: 'StyleIssues[]' },
        { name: 'post-review', description: 'Post review to GitHub', params: { review: 'Review' }, returns: 'void' },
      ],
    },
  },
  {
    id: 'slack-notifications',
    name: 'Slack Notifications',
    description: 'Send formatted notifications to Slack channels. Supports blocks, threads, and mentions.',
    version: '0.2.0',
    author: 'Community',
    category: 'communication',
    status: 'error',
    icon: '⊕',
    iconColor: '#4A154B',
    tags: ['slack', 'notifications', 'blocks', 'threads'],
    triggers: ['event:alert.created', 'manual'],
    actions: ['format-message', 'send-slack', 'thread-reply'],
    lastRun: '2d ago',
    nextRun: 'on alert',
    runCount: 12,
    successRate: 41.7,
    avgDuration: '3s',
    installDate: '2026-07-15',
    lastUpdate: '2026-07-15',
    size: '1.9 MB',
    repository: 'github.com/community/slack-notifications',
    manifest: {
      name: 'slack-notifications',
      version: '0.2.0',
      description: 'Slack notification delivery',
      author: 'Community',
      license: 'MIT',
      homepage: 'github.com/community/slack-notifications',
      keywords: ['slack', 'notifications', 'blocks', 'threads'],
      permissions: ['slack.token', 'chat.write', 'channels.read'],
      dependencies: { '@slack/bolt': '^3.0.0' },
      entryPoint: 'dist/index.js',
      configSchema: { defaultChannel: { type: 'string' }, useBlocks: { type: 'boolean', default: true }, threadReplies: { type: 'boolean', default: true } },
      triggers: [{ type: 'event', config: { event: 'alert.created' } }, { type: 'manual', config: {} }],
      actions: [
        { name: 'format-message', description: 'Format notification for Slack', params: { alert: 'Alert' }, returns: 'SlackMessage' },
        { name: 'send-slack', description: 'Send to Slack', params: { message: 'SlackMessage' }, returns: 'SendResult' },
        { name: 'thread-reply', description: 'Reply in thread', params: { threadTs: 'string', message: 'string' }, returns: 'void' },
      ],
    },
  },
]

export interface SkillTemplate {
  id: string
  name: string
  description: string
  category: Skill['category']
  icon: string
  iconColor: string
  boilerplate: string
}

export const SKILL_TEMPLATES: SkillTemplate[] = [
  {
    id: 'scheduled-task',
    name: 'Scheduled Task',
    description: 'Run a task on a cron schedule',
    category: 'automation',
    icon: '◴',
    iconColor: '#22d97a',
    boilerplate: `export default {
  name: 'my-scheduled-task',
  version: '1.0.0',
  description: 'Runs on a schedule',
  triggers: [{ type: 'schedule', config: { cron: '0 * * * *' } }],
  actions: [
    { name: 'run', description: 'Main task', params: {}, returns: 'Result' },
  ],
}`,
  },
  {
    id: 'event-handler',
    name: 'Event Handler',
    description: 'React to system events',
    category: 'automation',
    icon: '⚡',
    iconColor: '#ffb347',
    boilerplate: `export default {
  name: 'my-event-handler',
  version: '1.0.0',
  description: 'Handles system events',
  triggers: [{ type: 'event', config: { event: 'log.write' } }],
  actions: [
    { name: 'handle', description: 'Process event', params: { event: 'Event' }, returns: 'void' },
  ],
}`,
  },
  {
    id: 'webhook-receiver',
    name: 'Webhook Receiver',
    description: 'Receive and process incoming webhooks',
    category: 'integration',
    icon: '⊕',
    iconColor: '#00e5ff',
    boilerplate: `export default {
  name: 'my-webhook',
  version: '1.0.0',
  description: 'Receives webhooks',
  triggers: [{ type: 'webhook', config: { path: '/webhook/my-service' } }],
  actions: [
    { name: 'process', description: 'Process webhook', params: { payload: 'any' }, returns: 'Response' },
  ],
}`,
  },
  {
    id: 'multi-agent-workflow',
    name: 'Multi-Agent Workflow',
    description: 'Orchestrate multiple agents in sequence',
    category: 'automation',
    icon: '⌘',
    iconColor: '#d946ef',
    boilerplate: `export default {
  name: 'my-workflow',
  version: '1.0.0',
  description: 'Multi-agent workflow',
  triggers: [{ type: 'manual', config: {} }],
  actions: [
    { name: 'step1', description: 'First step', params: { input: 'string' }, returns: 'Output1' },
    { name: 'step2', description: 'Second step', params: { input: 'Output1' }, returns: 'Output2' },
    { name: 'step3', description: 'Final step', params: { input: 'Output2' }, returns: 'Result' },
  ],
}`,
  },
  {
    id: 'data-processor',
    name: 'Data Processor',
    description: 'Transform and process data',
    category: 'data',
    icon: '◧',
    iconColor: '#7c6cf5',
    boilerplate: `export default {
  name: 'my-processor',
  version: '1.0.0',
  description: 'Processes data',
  triggers: [{ type: 'manual', config: {} }],
  actions: [
    { name: 'fetch', description: 'Get data', params: {}, returns: 'RawData' },
    { name: 'transform', description: 'Transform data', params: { data: 'RawData' }, returns: 'ProcessedData' },
    { name: 'store', description: 'Store result', params: { data: 'ProcessedData' }, returns: 'void' },
  ],
}`,
  },
  {
    id: 'chat-command',
    name: 'Chat Command',
    description: 'Custom command for agent chat',
    category: 'communication',
    icon: '◌',
    iconColor: '#f06292',
    boilerplate: `export default {
  name: 'my-command',
  version: '1.0.0',
  description: 'Chat command',
  triggers: [{ type: 'manual', config: {} }],
  actions: [
    { name: 'execute', description: 'Run command', params: { args: 'string[]', context: 'Context' }, returns: 'string' },
  ],
}`,
  },
]

export const SKILL_NAV_LINKS: NavLink[] = [
  { id: 'skills-overview', label: 'Overview', icon: '◎', group: 'self' },
  { id: 'skills-installed', label: 'Installed', icon: '◧', group: 'self' },
  { id: 'skills-templates', label: 'Templates', icon: '⊕', group: 'self' },
  { id: 'skills-builder', label: 'Builder', icon: '⌘', group: 'self' },
  { id: 'skills-settings', label: 'Settings', icon: '⚙', group: 'self' },
]